add CMSSW_BASE/tmp to CMSSW_SEARCH_PATH so that unit test can use it for generated files

diff --git a/SCRAM/GMake/Makefile.rules b/SCRAM/GMake/Makefile.rules
--- a/SCRAM/GMake/Makefile.rules
+++ b/SCRAM/GMake/Makefile.rules
@@ -816,7 +816,8 @@ define run_test
     $(CMD_echo) "===== Test \"$(1)\" ====" >> $($(1)_objdir)/testing.log &&\
     STIME=$$(date +%s) &&\
     export SCRAM_TEST_NAME="$1" && export SCRAM_TEST_PATH="$(LOCALTOP)/$4" && export SCRAM_TEST_PACKAGE="$($(1)_PROD_PACKAGE)" && export SCRAM_TEST_PRE_TESTS="$($(1)_PRE_TEST)" &&\
-    export PATH=$(LOCALTOP)/$(4):$(UNIT_TEST_PATHS):$(PATH) && $(strip $($(1)_TEST_ENV)) (($(if $(strip $(${1}_USE_UNITTEST_DIR)),$(CMD_rm) -rf $(UNITTEST_DIR)/$1 && $(CMD_mkdir) -p $(UNITTEST_DIR)/$1 && cd $(UNITTEST_DIR)/$1 $(if $(strip $($(1)_PRE_TEST)),&& for d in $($(1)_PRE_TEST) ; do [ ! -d $(UNITTEST_DIR)/$$d ] || $(CMD_rsync) -a --link-dest=../$$d/ $(UNITTEST_DIR)/$$d/ ./; done) &&) $(if $(strip $(${1}_LOC_FLAGS_NO_TEST_PREFIX)),,$(EDM_TOOLS_PREFIX)) $(SCRAM_TEST_RUNNER_PREFIX) sh -c '$(subst ','\'',$(5))' && $(CMD_echo) "" && $(CMD_echo) "---> test $(1) succeeded") >> $($(1)_objdir)/testing.log 2>&1 || ($(CMD_echo) "" && $(CMD_echo) "---> test $(1) had ERRORS") >> $($(1)_objdir)/testing.log) &&\
+    export CMSSW_SEARCH_PATH=$(LOCALTOP)/tmp:$(CMSSW_SEARCH_PATH) &&\
+    export PATH=$(LOCALTOP)/$(4):$(UNIT_TEST_PATHS):$(PATH) && $(strip $($(1)_TEST_ENV)) (($(if $(strip $(${1}_USE_UNITTEST_DIR)),$(CMD_rm) -rf $(UNITTEST_DIR)/$1 && $(CMD_mkdir) -p $(UNITTEST_DIR)/$1 && export CMSSW_SEARCH_PATH=$(UNITTEST_DIR)/$1:$$CMSSW_SEARCH_PATH && cd $(UNITTEST_DIR)/$1 $(if $(strip $($(1)_PRE_TEST)),&& for d in $($(1)_PRE_TEST) ; do [ ! -d $(UNITTEST_DIR)/$$d ] || $(CMD_rsync) -a --link-dest=../$$d/ $(UNITTEST_DIR)/$$d/ ./; done) &&) $(if $(strip $(${1}_LOC_FLAGS_NO_TEST_PREFIX)),,$(EDM_TOOLS_PREFIX)) $(SCRAM_TEST_RUNNER_PREFIX) sh -c '$(subst ','\'',$(5))' && $(CMD_echo) "" && $(CMD_echo) "---> test $(1) succeeded") >> $($(1)_objdir)/testing.log 2>&1 || ($(CMD_echo) "" && $(CMD_echo) "---> test $(1) had ERRORS") >> $($(1)_objdir)/testing.log) &&\
     let UT_TIME=$$(date +%s)-$${STIME} || true &&\
     $(CMD_echo) "TestTime:$${UT_TIME}" >> $($(1)_objdir)/testing.log &&\
     $(CMD_echo) "^^^^ End Test $(1) ^^^^" >> $($(1)_objdir)/testing.log &&\
