allow to enable/disable seperate unit test directory

diff --git a/SCRAM/GMake/Makefile.rules b/SCRAM/GMake/Makefile.rules
--- a/SCRAM/GMake/Makefile.rules
+++ b/SCRAM/GMake/Makefile.rules
@@ -62,6 +62,7 @@ AREXT:=a
 MODULE_PREFIX:=lib
 COMMON_WORKINGDIR := $(SCRAM_TMP)/common
 WORKINGDIR := $(SCRAM_INTwork)
+USE_UNITTEST_DIR:=
 UNITTEST_DIRNAME:=unit_tests
 UNITTEST_DIR := $(LOCALTOP)/$(UNITTEST_DIRNAME)
 UNITTEST_TYPES:=
@@ -139,7 +140,7 @@ SYNTAX_ONLY:=$(if $(strip $(SCRAM_SYNTAX_ONLY)),YES,)
 ifneq ($(strip $(filter -fsyntax-only,$(USER_CXXFLAGS))),)
 SYNTAX_ONLY:=YES
 endif
-SKIP_SCRIPTS_COPY:=
+SKIP_SCRIPTS_COPY:=$(UNITTESTING)
 ifneq ($(strip $(filter skip-scripts-copy,$(MAKECMDGOALS))),)
   SKIP_SCRIPTS_COPY:=yes
 endif
@@ -824,15 +825,36 @@ define run_test
     $(CMD_echo) " " >> $($(1)_objdir)/testing.log &&\
     $(CMD_echo) "===== Test \"$(1)\" ====" >> $($(1)_objdir)/testing.log &&\
     STIME=$$(date +%s) &&\
-    export SCRAM_TEST_NAME="$1" && export SCRAM_TEST_PATH="$(LOCALTOP)/$4" && export SCRAM_TEST_PACKAGE="$($(1)_PROD_PACKAGE)" && export SCRAM_TEST_PRE_TESTS="$($(1)_PRE_TEST)" &&\
+    export SCRAM_TEST_NAME="$1" &&\
+    export SCRAM_TEST_PATH="$(LOCALTOP)/$4" &&\
+    export SCRAM_TEST_PACKAGE="$($(1)_PROD_PACKAGE)" &&\
+    export SCRAM_TEST_PRE_TESTS="$($(1)_PRE_TEST)" &&\
     export CMSSW_SEARCH_PATH=$(LOCALTOP)/tmp:$(CMSSW_SEARCH_PATH) &&\
-    export PATH=$(LOCALTOP)/$(4):$(UNIT_TEST_PATHS):$(PATH) && $(strip $($(1)_TEST_ENV)) (($(CMD_mkdir) -p $(UNITTEST_DIR)/$1 && export CMSSW_SEARCH_PATH=$(UNITTEST_DIR)/$1:$$CMSSW_SEARCH_PATH && cd $(UNITTEST_DIR)/$1 $(if $(strip $($(1)_PRE_TEST)),&& for d in $($(1)_PRE_TEST) ; do [ ! -d $(UNITTEST_DIR)/$$d ] || $(CMD_rsync) -a --link-dest=../$$d/ $(UNITTEST_DIR)/$$d/ ./; done) && $(if $(strip $(${1}_LOC_FLAGS_NO_TEST_PREFIX)),,$(EDM_TOOLS_PREFIX)) $(SCRAM_TEST_RUNNER_PREFIX) sh -c '$(subst ','\'',$(5))' && $(CMD_echo) "" && $(CMD_echo) "---> test $(1) succeeded") >> $($(1)_objdir)/testing.log 2>&1 || ($(CMD_echo) "" && $(CMD_echo) "---> test $(1) had ERRORS") >> $($(1)_objdir)/testing.log) &&\
+    export PATH=$(LOCALTOP)/$(4):$(UNIT_TEST_PATHS):$(PATH) &&\
+    $(strip $($(1)_TEST_ENV)) \
+    ((\
+      $(if $(strip $(${1}_USE_UNITTEST_DIR)),\
+          $(CMD_mkdir) -p $(UNITTEST_DIR)/$1 &&\
+          export CMSSW_SEARCH_PATH=$(UNITTEST_DIR)/$1:$$CMSSW_SEARCH_PATH &&\
+          cd $(UNITTEST_DIR)/$1 \
+          $(if $(strip $($(1)_PRE_TEST)),&&\
+              for d in $($(1)_PRE_TEST) ; do \
+                [ ! -d $(UNITTEST_DIR)/$$d ] || $(CMD_rsync) -a --link-dest=../$$d/ $(UNITTEST_DIR)/$$d/ ./; \
+              done\
+           ),\
+          true\
+       ) &&\
+      $(if $(strip $(${1}_LOC_FLAGS_NO_TEST_PREFIX)),,$(EDM_TOOLS_PREFIX))\
+      $(SCRAM_TEST_RUNNER_PREFIX) \
+      sh -c '$(subst ','\'',$(5))' &&\
+      $(CMD_echo) "" &&\
+      $(CMD_echo) "---> test $(1) succeeded") >> $($(1)_objdir)/testing.log 2>&1 || ($(CMD_echo) "" && $(CMD_echo) "---> test $(1) had ERRORS") >> $($(1)_objdir)/testing.log) &&\
     let UT_TIME=$$(date +%s)-$${STIME} || true &&\
     RESULT=$$($(CMD_grep) -q " test $(1) succeeded" $($(1)_objdir)/testing.log && $(CMD_echo) Pass || $(CMD_echo) Fail) &&\
     $(CMD_echo) "TestTime:$${UT_TIME}" >> $($(1)_objdir)/testing.log &&\
     $(CMD_echo) "^^^^ End Test $(1) ^^^^" >> $($(1)_objdir)/testing.log &&\
     $(CMD_sed) -i -e 's# \(Entering\|Leaving\)  *Package # \1 Recursive Package #g' $($(1)_objdir)/testing.log &&\
-    $(CMD_cp) -f $($(1)_objdir)/testing.log $(UNITTEST_DIR)/$1.log &&\
+    $(if $(strip $(${1}_USE_UNITTEST_DIR)),$(CMD_cp) -f $($(1)_objdir)/testing.log $(UNITTEST_DIR)/$1.log &&)\
     $(if $(strip $(SCRAM_BUILDVERBOSE)),$(CMD_cat) $($(1)_objdir)/testing.log &&)\
     $(CMD_printf) "$${RESULT} %5s ... $($(1)_PROD_PACKAGE)/$1\n" "$${UT_TIME}s" &&\
     $(CMD_cat) $($(1)_objdir)/testing.log >> $(LOCALTOP)/$(3)/testing.log; \
@@ -1042,6 +1064,19 @@ redirectlog_$(1) :=
 endif
 endef
 
+define UnitTestBuildDirectory
+${1}_USE_UNITTEST_DIR:=$(USE_UNITTEST_DIR)
+ifneq ($(strip $(USE_UNITTEST_DIR)),1)
+ifneq ($(strip $(${1}_LOC_FLAGS_USE_UNITTEST_DIR)),)
+ifneq ($(strip $(lastword $(${1}_LOC_FLAGS_USE_UNITTEST_DIR))),1)
+${1}_USE_UNITTEST_DIR:=
+else
+${1}_USE_UNITTEST_DIR:=1
+endif
+endif
+endif
+endef
+
 #safename,path,safepath,scriptstore,scripts,plugintype
 define CommonBinaryHead
 ifeq ($(strip $(filter %/src/alpaka,$2)),)
@@ -1094,6 +1129,7 @@ $$($(1)_objdir)/config: $$($(1)_CONFIGDEPS) | $(WORKINGDIR)/$(2)/productautoclea
 endif
 $(1)_config_msg += $(WORKINGDIR)/cache/msg/$(2)/$(1).msg $(if $(strip $(filter $($(3)_parent),$(ALL_PACKAGES))),$(WORKINGDIR)/cache/msg/$(SCRAM_SOURCEDIR)/$($(3)_parent).msg,)
 $(1)_config += $$($(1)_objdir)/config
+$(eval $(call UnitTestBuildDirectory,$1))
 ifneq ($(strip $($(1)_DNN_NAME)),)
 $$(eval $$(call AddDNNRules,$1,$2))
 endif
