Python module compilation errors are now treated as build errors for dev area. For release they are still treated as warnings

diff --git a/SCRAM/GMake/Makefile.rules b/SCRAM/GMake/Makefile.rules
--- a/SCRAM/GMake/Makefile.rules
+++ b/SCRAM/GMake/Makefile.rules
@@ -583,6 +583,10 @@ define compile_python
         $(VERB_ECHO) "python -c import $$mod";\
         ((cd $(4)/$$moddir && python -c "import $$mod") && [ -f $$pyc ] && touch -r $$py $$pyc) || err=1 ;\
       fi;\
+      if [ "X$$err" == "X1" ] ; then \
+        echo "Error: $$py: Python compilation error. Please fix it."; \
+        [ "X$RELEASETOP" != "X" ] && exit 1 ;\
+      fi;\
     fi;\
   done $(endlog_$(2))
 endef
