This commit was manufactured by cvs2svn to create tag 'V03-28-04'.
Sprout from master 2009-09-25 12:23:38 UTC muzaffar 'Improved logic to avoid linking against private test libraries'
Cherrypick from master 2009-10-07 12:35:49 UTC muzaffar 'Bug fix, make sure that all python modules of a package are compiled. Due to the bug it was stopping at the first compile error':
    SCRAM/GMake/Makefile.rules

diff --git a/SCRAM/GMake/Makefile.rules b/SCRAM/GMake/Makefile.rules
--- a/SCRAM/GMake/Makefile.rules
+++ b/SCRAM/GMake/Makefile.rules
@@ -585,18 +585,17 @@ define compile_python
       echo ">> Compiling: $$py";\
       if [ "`echo $$mod | grep '/'`X" == "X" ] ; then \
         $(VERB_ECHO) "python -c import $3.$$mod";\
-	(python -c "import $3.$$mod" && [ -f $$pyc ] && touch -r $$py $$pyc) || err=1 ;\
+	((python -c "import $3.$$mod" && [ -f $$pyc ] && touch -r $$py $$pyc) || (echo "Error: $$py: Python compilation error. Please fix it." && err=1)) ;\
       else \
         moddir=`dirname $$mod`; mod=`basename $$mod`;\
         $(VERB_ECHO) "python -c import $$mod";\
-        ((cd $(4)/$$moddir && python -c "import $$mod") && [ -f $$pyc ] && touch -r $$py $$pyc) || err=1 ;\
-      fi;\
-      if [ "X$$err" == "X1" ] ; then \
-        echo "Error: $$py: Python compilation error. Please fix it."; \
-        [ "X$RELEASETOP" != "X" ] && exit 1 ;\
+        (((cd $(4)/$$moddir && python -c "import $$mod") && [ -f $$pyc ] && touch -r $$py $$pyc) || (echo "Error: $$py: Python compilation error. Please fix it." && err=1)) ;\
       fi;\
     fi;\
-  done $(endlog_$(2))
+  done; \
+  if [ "X$$err" == "X1" ] ; then \
+    [ "X$(RELEASETOP)" = "X" ] || exit 1 ;\
+  fi $(endlog_$(2))
 endef
 
 ##############################################################################
