backported unitests run for 44X

diff --git a/SCRAM/GMake/Makefile.rules b/SCRAM/GMake/Makefile.rules
--- a/SCRAM/GMake/Makefile.rules
+++ b/SCRAM/GMake/Makefile.rules
@@ -753,17 +753,18 @@ endef
 # Tesings test executable
 define run_test
   @if [ "X$($(1)_NO_TESTRUN)" == "Xyes" ] ; then \
-    $(CMD_echo) "Package "$(patsubst src/%/test,%,$(4))": Skipping test $(1)"; \
+    $(CMD_echo) "Package "$(patsubst $(SCRAM_SOURCEDIR)/%/test,%,$(4))": Skipping test $(1)"; \
   else \
-    $(CMD_echo) "Package "$(patsubst src/%/test,%,$(4))": Running test $(1)" &&\
+    $(CMD_echo) "Package "$(patsubst $(SCRAM_SOURCEDIR)/%/test,%,$(4))": Running test $(1)" &&\
+    [ -d $($(1)_objdir) ] || $(CMD_mkdir) -p $($(1)_objdir) &&\
     $(CMD_rm) -f $($(1)_objdir)/testing.log; $(CMD_touch) $($(1)_objdir)/testing.log  &&\
     $(CMD_echo) " " >> $($(1)_objdir)/testing.log &&\
     $(CMD_echo) "===== Test \"$(1)\" ====" >> $($(1)_objdir)/testing.log &&\
-    export PATH=$(LOCALTOP)/$(2):$(LOCALTOP)/$(4):$(PATH) && (($($(1)_TEST_RUNNER_CMD)) >> $($(1)_objdir)/testing.log 2>&1 || $(CMD_echo) "---> test $(1) had ERRORS") &&\
+    export PATH=$(LOCALTOP)/$(2):$(LOCALTOP)/$(4):$(PATH) && (($($(1)_TEST_RUNNER_CMD)) >> $($(1)_objdir)/testing.log 2>&1 || ($(CMD_echo) "" && $(CMD_echo) "---> test $(1) had ERRORS") >> $($(1)_objdir)/testing.log) &&\
     $(CMD_echo) " " >> $($(1)_objdir)/testing.log &&\
     $(CMD_echo) "^^^^ End Test $(1) ^^^^" >> $($(1)_objdir)/testing.log &&\
     $(CMD_cat) $($(1)_objdir)/testing.log &&\
-    $(CMD_cat) $($(1)_objdir)/testing.log >> $(LOCALTOP)/$(3)/testing.log; $(CMD_rm) -f $($(1)_objdir)/testing.log; \
+    $(CMD_cat) $($(1)_objdir)/testing.log >> $(LOCALTOP)/$(3)/testing.log; \
   fi
 endef
 
@@ -789,10 +790,12 @@ define get_time_stamp
 endef
 #############################################################################
 define SubSystem
-.PHONY: $(1) src/$(1) $(2) all_$(2) runtests_$(2) compile_$(2) precompile_$(2)
+.PHONY: $(1) src/$(1) $(2) all_$(2) runtests_$(2) unittests_$(2) compile_$(2) precompile_$(2)
 $(1) src/$(1) $(2) all_$(2): $(subdirs_$(2))
 	@$(CMD_echo) ">> Subsystem $(1) built"
 runtests_$(2): $(addprefix runtests_,$(subdirs_$(2)))
+	@:
+unittests_$(2): $$(addprefix unittests_,$$(subdirs_$(2)))
 	@:
 runpython_$(2): $(addprefix runpython_,$(subdirs_$(2)))
 	@:
@@ -813,7 +816,7 @@ $(WORKINGDIR)/cache/prod/lib$(1): $($(1)_BuildFile) $$($(1)_libdeps)
 	@$(CMD_touch) $$@
 endef
 define Package
-.PHONY: $(1) src/$(1) $(2) all_$(2) runtests_$(2) msg_$(2) compile_$(2) precompile_$(2)
+.PHONY: $(1) src/$(1) $(2) all_$(2) runtests_$(2) unittests_$(2) msg_$(2) compile_$(2) precompile_$(2)
 ifeq ($(strip $(BUILD_LOG)),yes)
 logfile_$(2) := $(WORKINGDIR)/cache/log/src/$(1)/build.log
 redirectlog_$(2) := >> $(WORKINGDIR)/cache/log/src/$(1)/build.log
@@ -833,6 +836,8 @@ $(1) src/$(1) $(2) all_$(2): msg_$(2) $(addprefix all_,$(subdirs_$(2)))
 	$(CMD_echo) ">> Package $(1) built"
 ifeq ($$(filter $(2)_test,$(subdirs_$(2))),$(2)_test)
 runtests_$(2): $(2) runtests_$(2)_test
+	@$(CMD_echo) ">> Tests for package $(1) ran."
+unittests_$(2): unittests_$(2)_test
 	@$(CMD_echo) ">> Tests for package $(1) ran."
 endif
 precompile_$(2): $(addprefix precompile_,$(subdirs_$(2)))
@@ -959,12 +964,15 @@ ifeq ($(strip $(4)),python)
 endif
 ifeq ($(strip $(4)),test)
 	$$(call build_test,$(1),$(1),$(3),TEST)
-.PHONE: runtests_$(1)
+.PHONE: runtests_$(1) unittests_$(1)
 ifeq ($$(strip $$(filter $(1),$(SKIP_UNITTESTS))),$(1))
 $(1)_NO_TESTRUN := yes
 endif
 runtests_$(6) += runtests_$(1)
-runtests_$(1): all_$(1) $(LOCALTOP)/$(5)/testing.log
+unittests_$(6) += unittests_$(1)
+runtests_$(1): all_$(1) unittests_$(1)
+	$$(call run_test,$(1),$(3),$(5),$(2))
+unittests_$(1): $(patsubst %,runtests_%,$($(1)_PRE_TEST)) $(LOCALTOP)/$(5)/testing.log
 	$$(call run_test,$(1),$(3),$(5),$(2))
 endif
 $(WORKINGDIR)/cache/prod/$(1): $($(1)_objdir)/$($(1)_product)
@@ -1207,9 +1215,11 @@ endef
 define CommonProductRules
 .PHONY: $(1) all_$(1)
 ifeq ($(strip $(3)),TEST)
-.PHONY: runtests_$(1)
+.PHONY: runtests_$(1) unittests_$(1)
 $(1) += $($(1)_data_copy_rule)
 runtests_$(1): $(1) $(runtests_$(1))
+	@:
+unittests_$(1): $(unittests_$(1))
 	@:
 endif
 $(1) all_$(1): $($(1))
@@ -1509,11 +1519,12 @@ all: all_$(TARGETDIR)
 project project_all all_$(SCRAM_SOURCEDIR): $(SCRAM_SOURCEDIR)
 	@:
 
-.PHONY: python help compile precompile runtests clean distclean cache_clean project_clean project_help 
+.PHONY: python help compile precompile runtests unittests clean distclean cache_clean project_clean project_help 
 .PHONY: clean_$(SCRAM_SOURCEDIR) help_$(SCRAM_SOURCEDIR)
 help: help_$(TARGETDIR)
 clean: clean_$(TARGETDIR)
 runtests: runtests_$(TARGETDIR)
+unittests: unittests_$(TARGETDIR)
 python: runpython_$(TARGETDIR)
 compile: compile_$(TARGETDIR)
 precompile: precompile_$(TARGETDIR)
@@ -1558,6 +1569,9 @@ project_help help_$(SCRAM_SOURCEDIR):
 	@$(CMD_echo) "runtests:"
 	@$(CMD_echo) "     Build and run all tests for the project, or package-level tests only."
 	@$(CMD_echo) "     (Depends on the location where \"scram b runtests\" is run)."
+	@$(CMD_echo) ""
+	@$(CMD_echo) "unittests:"
+	@$(CMD_echo) "     Same as runtests but does not try to build the test first."
 	@$(CMD_echo) ""
 
 .PHONY: release release-build release-reset release-check release-test release-doc release-docs release-freeze
@@ -1628,7 +1642,7 @@ $(foreach dir,$(ALL_SUBSYSTEMS),$(eval $(call SubSystem,$(dir),src_$(subst /,_,$
 $(foreach dir,$(ALL_PACKAGES),$(eval $(call Package,$(dir),src_$(subst /,_,$(dir)))))
 endif
 ###########################################################
-PHONY: $(SCRAM_SOURCEDIR) prebuild postbuild runtests_$(SCRAM_SOURCEDIR) runpython_$(SCRAM_SOURCEDIR) compile_$(SCRAM_SOURCEDIR) precompile_$(SCRAM_SOURCEDIR)
+PHONY: $(SCRAM_SOURCEDIR) prebuild postbuild runtests_$(SCRAM_SOURCEDIR) unittests_$(SCRAM_SOURCEDIR) runpython_$(SCRAM_SOURCEDIR) compile_$(SCRAM_SOURCEDIR) precompile_$(SCRAM_SOURCEDIR)
 $(SCRAM_SOURCEDIR): prebuild $($(SCRAM_SOURCEDIR)) $(subdirs_$(SCRAM_SOURCEDIR))
 	@$(DO_BUILD_LOG) $(MAKE) -f $(SCRAM_MAKEFILE) ufast outputlog
 	@$(MAKE) -f $(SCRAM_MAKEFILE) PostBuild
@@ -1640,6 +1654,8 @@ postbuild: $(postbuild) release-check
 runpython_$(SCRAM_SOURCEDIR): $(addprefix runpython_, $(subdirs_$(SCRAM_SOURCEDIR)))
 	@$(CMD_echo) ">> Python completed for $(SCRAM_PROJECTNAME) $(SCRAM_PROJECTVERSION)"
 runtests_$(SCRAM_SOURCEDIR): $(addprefix runtests_, $(subdirs_$(SCRAM_SOURCEDIR)))
+	@$(CMD_echo) ">> Test sequence completed for $(SCRAM_PROJECTNAME) $(SCRAM_PROJECTVERSION)"
+unittests_$(SCRAM_SOURCEDIR): $(addprefix unittests_, $(subdirs_$(SCRAM_SOURCEDIR)))
 	@$(CMD_echo) ">> Test sequence completed for $(SCRAM_PROJECTNAME) $(SCRAM_PROJECTVERSION)"
 compile_$(SCRAM_SOURCEDIR): $(addprefix compile_, $(subdirs_$(SCRAM_SOURCEDIR)))
 	@$(CMD_echo) ">> Compile sequence completed for $(SCRAM_PROJECTNAME) $(SCRAM_PROJECTVERSION)"
@@ -1726,7 +1742,7 @@ endef
 endif
 ###########################################################
 
-.PHONY: all_% clean_% help_% runtests_% runpython_% compile_% precompile_% ufast xfast fast %_USED_BY %_USES echo_% outputlog
+.PHONY: all_% clean_% help_% runtests_% unittests_% runpython_% compile_% precompile_% ufast xfast fast %_USED_BY %_USES echo_% outputlog
 .PHONY: help_%_python help_%_src help_%_plugins help_%_bin help_%_test help_$(SCRAM_SOURCEDIR)_%
 .PHONY: skiptest_%
 help_%_python:
@@ -1741,7 +1757,7 @@ help_%_test:
 	@$(CMD_echo) "Running \"scram build\" here normally build test executables and shared libs (if any)."
 help_$(SCRAM_SOURCEDIR)_%:
 	@$(CMD_echo) "Doing \"scram build\" here will build every thing exist under this directory."
-all_% runtests_% help_% runpython_% compile_% precompile_%:
+all_% runtests_% unittests_% help_% runpython_% compile_% precompile_%:
 	@if [ "X$(TARGETDIR)" = "X$*" ] ; then \
 	  $(CMD_echo) ">> Nothing to be done for $(THISDIR)";\
 	fi
